### PR TITLE
Hans iv

### PR DESCRIPTION
**Pull request by annanuran**
Date scraping is now functional, and GroupBuy Objects now contain a meaningful attribute relating to the end of the group buy, whether it is date focused or unit limited. Not perfect, as it won't catch "until production capacity reached" or "until sold through," but it works to get the dates for GBs.

Most, if not all, variable and method names have been refactored to adhere to PEP8 guidelines.

Next in the pipeline are useful docstrings,  image links, and purchase types.

### CODE REVIEW

**Comment by ff-zhang** [comment]
Can you remove the venv and \_\_pycache__ files from the pr. I think most of them were introduced in the [second commit](https://github.com/Keebapp/mechgroupbuys-reddit-scraper/pull/1/commits/05a18f12952a4479a66fd33df3b486c9e2543159)

**Comment by ff-zhang** [comment]
Additionally, what is the .idea folder for? Should it be commited to the repo?

**Comment by leviwaiu** [comment]
.idea folder is for the IntelliJ suite of IDEs. It should be omitted from the commit, and be added into the gitignore list.

**Comment by annanuran** [comment]
Fixed. gitignore updated, venv and .idea removed

**Comment by ff-zhang** [comment]
Great! Can you also remove that __pycache__ folder and rename the rest of the functions in main.py to adhere to PEP 8. With the exception of those two things, everything seems to good.

**Comment by annanuran** [comment]
Done.

**Review by ff-zhang — APPROVED** [review]

**Pull request merged**
